# Generated by Django 4.2 on 2023-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_app', '0003_avatar_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='imagenInstrumento',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
    ]
