# Generated by Django 4.2 on 2023-10-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_app', '0004_disco_imageninstrumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='imagenInstrumento',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='precio',
        ),
        migrations.AddField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
    ]
