# Generated by Django 4.2 on 2023-10-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_app', '0005_remove_disco_imageninstrumento_remove_disco_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
