# Generated by Django 4.2 on 2023-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_app', '0006_disco_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
