# Generated by Django 4.2 on 2023-10-20 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda_app', '0007_alter_disco_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
    ]
