# Generated by Django 4.2 on 2023-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_app', '0008_disco_user_alter_disco_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='descripcion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
