# Generated by Django 4.2 on 2023-10-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_app', '0009_disco_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
